rambler-digital-solutions/airflow-declarative

src/airflow_declarative/schema.py, src/airflow_declarative/trafaret.py, tests/dags/good/email.yaml, tests/dags/good/version.yaml, tests/dags/schema-errors/bad-email.yaml, tests/dags/schema-errors/bad-version.yaml
Add support for `trafaret<2,>=1.0`.
The following changes made since trafaret 0.10 have been accounted in this PR:
1. `Dict.check` method must be called for retrieving a value instead of `Dict.check_and_return`, which essentially is just a wrapper for the `check_and_return` \[1\].
2. `Email` trafaret must be created without parenthesis \[2\].
3. `Dict.make_optional` has been deprecated in favor of using explicit `Key(..., optional=True)` instances. It's still supported, but issues a warning. I applied the substitution to all specific optional keys, ~~but I didn't change the `.make_optional('*')` calls, because I don't like the idea of wrapping \~30 keys of the OPERATOR_ARGS schema to explicit `Key(..., optional=True)`. I asked in https://github.com/Deepwalker/trafaret/issues/44 if there's …
=> Update trafaret to 1.2.0

src/airflow_declarative/schema.py, tests/test_callback_tasks.py
According to the docs \[1\] airflow accepts `poke_interval` only as an `int`, but declarative was treating it as a timedelta.
\[1\]: https://airflow.apache.org/code.html#airflow.sensors.base_sensor_operator.BaseSensorOperator
=> Fix invalid `poke_interval` type: it must be int instead of timedelta

tests/test_bad_dags.py
The warning fixed there is the following one:
```
tests/test_bad_dags.py:70: RemovedInPytest4Warning: While trying to determine id of parameter expected_exception at position 14 the following exception was raised:
TypeError: expected str, bytes or os.PathLike object, not tuple
This warning will be an error error in pytest-4.0.
```
The issue was that an exception or a tuple of them being passed to the pytest's `param_id` function caused a `TypeError` being raised when calling `os.path.basename`. Apparently this line should be executed for strings only (to strip off the full path to the DAG yamls).
=> Fix a pytest warning

README.rst, tox-pip9.sh, tox.ini
Airflow 1.8 is quite old now so I think it should be ok to drop its support.
This allows to get rid of a horrible hack with the `tox-pip9.sh` script.
=> Drop Airflow 1.8 support

src/airflow_declarative/schema.py, tests/dags/good/executor-config.yaml
Some Airflow BaseOperator args were missing in the schema. This PR adds them.
The upstream API reference: https://airflow.apache.org/_api/airflow/models/index.html#airflow.models.BaseOperator
=> Add some missing keys to `OPERATOR_ARGS` like `task_concurrency`

src/airflow_declarative/schema.py, src/airflow_declarative/transformer.py, tests/dags/good/template-with-from-stdout.yaml, tests/dags/schema-errors/bad-with-items-both-using-and-from-stdout.yaml, tests/test_template_with_from_stdout.py
We already have `using` for `with_items` which calls a Python callback for filling the `with_items` list.
This PR adds another option -- `from_stdout` -- which calls an external command for doing the same.
There's a usage example in the tests.
=> Add `from_stdout` option to `with_items` which calls an external command

src/airflow_declarative/schema.py, tests/dags/schema-errors/bad-default-args.yaml
This PR fixes a bug which causes all non-existing keys of `default_args` to be treated as valid.
`allow_extra` mutates the trafaret `Dict` instance in-place; which definitely wasn't intended here.
=> Fix dag->args->default_args schema erroneously accepting extra dict keys

src/airflow_declarative/transformer.py, tests/dags/good/template-with-complex-jinja.yaml, tests/test_template_with_complex_jinja.py, tests/utils.py
For such templates there was an exception:
TypeError: unsupported operand type(s) for +: 'int' and 'str'
The reason is that we implicitly append `| yaml` to jinja templates in `with_items`, so the template starts to look like `{{ 1 + item.value | yaml }}`, which is effectively an "int + str" expression.
This commit fixes that by implicitly wrapping all templates in parens, so the aforementioned template would become `{{ (1 + item.value) | yaml }}`.
=> Fix `with_items` raising TypeError for jinja like `{{ 1 + item.value }}`

setup.py
Airflow shouldn't be installed when installing `airflow-declarative`, otherwise this causes a circular dependency when using a patched Airflow. See #24
=> setup.py: drop Airflow from `install_requires`

patches/1.10.4.patch
This PR adds a patch for Airflow 1.10.4rc2 which I'm currently using to add a built-in support for declarative dags (instead of the Python DAG shim given in the Readme).
I run my Airflow in Docker (a forked variant of https://github.com/puckel/docker-airflow). To apply this patch, I had to change the following in my Dockerfile:
```
--- a/Dockerfile
+++ b/Dockerfile
@@ -19,6 +19,8 @@ ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8
+COPY patch /root/patch
+
RUN set -ex \
&& buildDeps=' \
freetds-dev \
@@ -50,7 +52,14 @@ RUN set -ex \
&& pip install pyOpenSSL \
&& pip install ndg-httpsclient \
&& pip install pyasn1 \
-    && pip install apache-airflow[crypto,celery,postgres,jdbc,mysql,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
+    && pip install …
```
=> Add patch for 1.10.4rc2

src/airflow_declarative/schema.py, src/airflow_declarative/trafaret.py, tests/dags/good/schedule-interval-cron-preset.yaml, tests/dags/good/schedule-interval-none.yaml
Dag schedule_interval in airflow except cron expression and timedelta may be None or cron preset. 
This PR adds this two schedule_interval formats.
=> Add support for different schedule intervals formats

src/docs/index.rst, src/docs/reference.rst, src/docs/testing.rst
This PR adds a new doc page describing our approach for testing declarative DAGs at Usermodel.
This branch is deployed at https://airflow-declarative.readthedocs.io/en/add-testing-doc/testing.html
=> Add `testing` doc page

src/airflow_declarative/__init__.py, tests/test_good_dags.py
Render function transform yaml with dags. It's pretty useful but its usefulness limited only with printing yaml to stdout. If this function have return, this limitation will be removed.
This PR adds return value for render function.
=> Add return for render function

src/airflow_declarative/schema.py, src/docs/reference.rst
There was an error in schema at the reference page, this PR would fix it.
=> Reference doc: fix incorrect `defaults` schema

patches/1.10.5.patch, patches/1.10.6.patch
1.10.6 is currently a release candidate.
1.10.5 is already released, I tested that patch with an actual Airflow -- it seems to work fine.
There are two commits: one which contains just copies of the previous patch, and another which contains updates. It's easier to review by looking at the second commit.
=> Add new patches for 1.10.5 and 1.10.6

README.rst, src/docs/index.rst, src/docs/installation.rst
This PR adds a new "Installation" page to the docs.
This branch is currently deployed here: https://airflow-declarative.readthedocs.io/en/add-installation-docs/installation.html
After this PR would be merged I think we should remove almost everything from the README and then just direct people to the docs from there.
The "Option 2" section assumes that #24 is merged, so it would be nice to merge that first.
Ref #1
=> Docs: add `installation` page

.gitignore, MANIFEST.in, setup.cfg, setup.py, tests/test_metadata.py, tox.ini
There're 2 commits here:
1. I brought some minor changes from um/new-python-project making this project closer to that template
2. I converted from setup.py to setup.cfg
The latter change would require a more recent setuptools version on the consumers side, but usually this is not a problem, unless the target platform is using ancient versions of setuptools or Python.
=> Convert to setup.cfg

src/docs/testing.rst
I noticed that the testing doc contains an incorrect import. This PR fixes that.
=> Testing doc: fix incorrect import in the example

patches/1.10.10.patch, patches/1.10.9.patch
Basically they're the same as the previous ones, except that they now include YAML lexer patch for the RBAC UI too.
I have tested both patches manually.
Glad to report that airflow-declarative is also compatible with dag serialization and dag code serialization (as of 1.10.10)!
=> Add patches for 1.10.9 and 1.10.10

.travis.yml, src/airflow_declarative/builder.py, src/airflow_declarative/compat.py, src/airflow_declarative/schema.py, tests/test_bad_dags.py, tox.ini
Airflow has added new DAG and task args which are currently not supported by airflow-declarative.
Relevant Airflow docs:
- https://airflow.apache.org/docs/stable/_api/airflow/models/index.html#airflow.models.DAG
- https://airflow.apache.org/docs/stable/_api/airflow/models/index.html#airflow.models.BaseOperator
I checked only the `tags` field (I don't need the other ones) -- it works fine.
=> Add missing task and DAG args from the newer Airflow versions
